image: gitpod/workspace-python-3.12  # Базовый образ с Python

tasks:
  - name: Backend API
    init: |
      pip install -r ./requirements.txt
    command: |
      source .venv/bin/activate
      cd ./back/
      uvicorn main:app --reload

ports:
  - port: 5000  # Порт вашего бэкенда (измените под ваш случай)
    onOpen: open-preview
    visibility: public  # Критично для доступа из Telegram!


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true